import matplotlib.pyplot as plt
import numpy as np

# https://www.service-public.gouv.fr/particuliers/vosdroits/F35794

# Son / grand son / parents
TAX_DIRECT_DEDUCTION = 100000
TAX_DIRECT_5 = 0.05
TAX_DIRECT_5_MAX = 8072
TAX_DIRECT_10 = 0.1
TAX_DIRECT_10_MAX = 12109
TAX_DIRECT_15 = 0.15
TAX_DIRECT_15_MAX = 15932
TAX_DIRECT_20 = 0.2
TAX_DIRECT_20_MAX = 552324
TAX_DIRECT_30 = 0.3
TAX_DIRECT_30_MAX = 902838
TAX_DIRECT_40 = 0.4
TAX_DIRECT_40_MAX = 1805677
TAX_DIRECT_45 = 0.45

# Brother / Sister
TAX_FIRST_DEGREE_DEDUCTION = 15932
TAX_FIRST_DEGREE_35 = 0.35
TAX_FIRST_DEGREE_35_MAX = 24430
TAX_FIRST_DEGREE_45 = 0.45

# AV
TAX_AV_DEDUCTION = 152500
TAX_AV_20 = 0.2
TAX_AV_20_MAX = 700000
TAX_AV_3125 = 0.3125

# Return tax for the given capital with direct bloodline
def tax_direct(capital) -> float:

    results = 0.0

    # x <= 0 
    if capital <= TAX_DIRECT_DEDUCTION:
        result = 0.0
    
    # 0 < x <= 5
    elif TAX_DIRECT_DEDUCTION < capital and capital <= TAX_DIRECT_DEDUCTION + TAX_DIRECT_5_MAX:
        result = (capital-TAX_DIRECT_DEDUCTION)*TAX_DIRECT_5

    # 5 < x <= 10
    elif TAX_DIRECT_DEDUCTION + TAX_DIRECT_5_MAX < capital and capital <= TAX_DIRECT_DEDUCTION + TAX_DIRECT_10_MAX:
        result = (capital - TAX_DIRECT_5_MAX - TAX_DIRECT_DEDUCTION)*TAX_DIRECT_10 + TAX_DIRECT_5_MAX*TAX_DIRECT_5

    # 10 < x <= 15
    elif TAX_DIRECT_DEDUCTION + TAX_DIRECT_10_MAX < capital and capital <= TAX_DIRECT_DEDUCTION + TAX_DIRECT_15_MAX:
        result = (capital - TAX_DIRECT_10_MAX - TAX_DIRECT_DEDUCTION)*TAX_DIRECT_15 + (TAX_DIRECT_10_MAX-TAX_DIRECT_5_MAX)*TAX_DIRECT_10 + TAX_DIRECT_5_MAX*TAX_DIRECT_5

    # 15 < x <= 20
    elif TAX_DIRECT_DEDUCTION + TAX_DIRECT_15_MAX < capital and capital <= TAX_DIRECT_DEDUCTION + TAX_DIRECT_20_MAX:
        result = (capital - TAX_DIRECT_15_MAX - TAX_DIRECT_DEDUCTION)*TAX_DIRECT_20 + (TAX_DIRECT_15_MAX-TAX_DIRECT_10_MAX)*TAX_DIRECT_15 + (TAX_DIRECT_10_MAX-TAX_DIRECT_5_MAX)*TAX_DIRECT_10 + TAX_DIRECT_5_MAX*TAX_DIRECT_5

    # 20 < x <= 30
    elif TAX_DIRECT_DEDUCTION + TAX_DIRECT_20_MAX < capital and capital <= TAX_DIRECT_DEDUCTION + TAX_DIRECT_30_MAX:
        result = (capital - TAX_DIRECT_20_MAX - TAX_DIRECT_DEDUCTION)*TAX_DIRECT_30 + (TAX_DIRECT_20_MAX-TAX_DIRECT_15_MAX)*TAX_DIRECT_20 + (TAX_DIRECT_15_MAX-TAX_DIRECT_10_MAX)*TAX_DIRECT_15 + (TAX_DIRECT_10_MAX-TAX_DIRECT_5_MAX)*TAX_DIRECT_10 + TAX_DIRECT_5_MAX*TAX_DIRECT_5

    # 30 < x <= 40
    elif TAX_DIRECT_DEDUCTION + TAX_DIRECT_30_MAX < capital and capital <= TAX_DIRECT_DEDUCTION + TAX_DIRECT_40_MAX:
        result = (capital - TAX_DIRECT_30_MAX - TAX_DIRECT_DEDUCTION)*TAX_DIRECT_40 + (TAX_DIRECT_30_MAX-TAX_DIRECT_20_MAX)*TAX_DIRECT_30 + (TAX_DIRECT_20_MAX-TAX_DIRECT_15_MAX)*TAX_DIRECT_20 + (TAX_DIRECT_15_MAX-TAX_DIRECT_10_MAX)*TAX_DIRECT_15 + (TAX_DIRECT_10_MAX-TAX_DIRECT_5_MAX)*TAX_DIRECT_10 + TAX_DIRECT_5_MAX*TAX_DIRECT_5

    # 40 < x
    else:
        result = (capital - TAX_DIRECT_40_MAX - TAX_DIRECT_DEDUCTION)*TAX_DIRECT_45 + (TAX_DIRECT_40_MAX-TAX_DIRECT_30_MAX)*TAX_DIRECT_40 + (TAX_DIRECT_30_MAX-TAX_DIRECT_20_MAX)*TAX_DIRECT_30 + (TAX_DIRECT_20_MAX-TAX_DIRECT_15_MAX)*TAX_DIRECT_20 + (TAX_DIRECT_15_MAX-TAX_DIRECT_10_MAX)*TAX_DIRECT_15 + (TAX_DIRECT_10_MAX-TAX_DIRECT_5_MAX)*TAX_DIRECT_10 + TAX_DIRECT_5_MAX*TAX_DIRECT_5

    return round(result, 2)

print(tax_direct(100000))